name: Build & Push Frontend
on: [push]
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: |
          docker build -t acrportfoliose.azurecr.io/frontend-web:$GITHUB_SHA .
      - name: Login to ACR
        uses: azure/docker-login@v2
        with:
          login-server: acrportfoliose.azurecr.io
      - run: docker push acrportfoliose.azurecr.io/frontend-web:$GITHUB_SHA
